# Generated by Django 4.1.5 on 2023-01-31 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='name',
            new_name='band',
        ),
    ]
