# Generated by Django 4.1.5 on 2023-02-01 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_name_poster_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('option', models.CharField(choices=[('F', 'Foil'), ('B', 'Bleached'), ('N', 'Natural'), ('C', 'Color')], default='F', max_length=1)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.poster')),
            ],
        ),
    ]
