# Generated by Django 4.1.5 on 2023-02-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_dream_alter_variation_options_alter_variation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='dream',
            field=models.ManyToManyField(to='main_app.dream'),
        ),
    ]
